### ISSUE TITLE
isparta and test unit issues

### ISSUE THREAD

**Issue by himalayafan** [alferov/generator-ujsm#1]
Hey! Great work, but I encounter issues on windows. isparta refuse to run.

**Failed at the xxx@1.0.0 coverage script 'isparta cover _mocha -- --require babel-core/register'.**

When I try to do this **npm run test-browser**, I get this:

**'.' is not recognized as an internal or external command,
operable program or batch file.**

**Comment by alferov** [comment]
Hi, thank you!
What type of shell are you using? cmd?
I'll properly test it on Windows tomorrow (anyways, I intended to :sweat_smile: )

**Comment by himalayafan** [comment]
Hi. I know windows have a lot of flaws. So not your fault :) To avoid all issues, I always run Git shell. It have never given me an issue. However. Now I got the errors I mentioned, plus a few errors regarding **gylp** when I do a clean install.

Node 5 seems to be ok, but npm 3.3.6 seems to be buggy for me.

**Comment by himalayafan** [comment]
In case it helps, here are part of the log.

les\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python27\python.exe -c import platform; print(platform.python_version());
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:203:12)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:469:12)

**Comment by alferov** [comment]
Thanks, I'll test it this afternoon

**Comment by alferov** [comment]
I updated npm scripts caused issues. 
> gyp ERR! stack Error: Command failed: C:\Python27\python.exe -c import platform; 

It looks like it was looking for python. I found a similar issue on stackoverflow: http://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm 
So it's better to have that dependencies to be installed.

Please, update the generator:
`npm i -g generator-ujsm`

**Comment by himalayafan** [comment]
Hey. Yes, the issues solved. Thanks :) 
However I noticed that in my test build I had up online earlier, coveralls.io doesn't get updated at all, but excited with 0. So everything seems okey.
