### ISSUE TITLE
where is the configuration for server side tests?

### ISSUE THREAD

**Issue by himalayafan** [alferov/generator-ujsm#3]
Hey. Is there any configuration files for the server side?  Exampleon what I mean: https://github.com/babel/generator-babel-boilerplate/tree/master/app/templates/test/setup

Example if I need to set up jsDom or similar. Such setup as linked to, would prevent you from inlcuding chai in each file too. 

Any fixtures?

**Comment by alferov** [comment]
Currently it's just a npm script.
It's a definitely good idea to encapsulate configs in a separate file. :+1:
