### ISSUE TITLE
wrapped up inside default

### ISSUE THREAD

**Issue by himalayafan** [alferov/generator-ujsm#5]
Hi. Another issue :) Seems like if I try to use this as isomorphic, and don't specify a file name after 'src' in the `webpack config` ( *it should automatically swap between server.js and index.js*) it wraps the output in default.

Let say we got a `export default {}` in the `index.js` file.

If you output the compiled source, you will see that the object have been wrapped inside default.

 `Object { default={...}}`

Not sure what is going on here, but I don't need any default. Only access to the object literal itself.

However. I didn't try this directly to check if the same issue happen if I example do this: `src/index.js` in the `webpack config`

**Comment by alferov** [comment]
Which version of Babel are you using?
It's a new behaviour of Babel 6:
https://github.com/babel/babel/issues/2212
https://github.com/babel/babel/issues/2724

This generator intentionally uses [Babel 5.8.3](https://github.com/alferov/generator-ujsm/blob/master/app/templates/_package.json#L25) (just for now, though) to keep old CommonJS way of exporting stuff.

**Comment by himalayafan** [comment]
Hi. I'm online quickly to reply. In my attempt to figure out a few issues I faced, I looked into your commit log and saw you had used Babel 6.x. So I tried that one and got this issue. I reverted back and now I'm using your new setup with Babel 5.x.  So issue solved.

**Comment by alferov** [comment]
Okay, It's good that you solved it.
I'm closing this one.

**Comment by himalayafan** [comment]
Just add to the record, that you now can use `module.exports = { … }` instead of `export default` to get the same behaviour as in prev versions.

**Comment by alferov** [comment]
I was thinking about it.
Another thought:
`module.js`:
```js
export function myShinyModule() {

}
``` 

`index.js`:
```js
var myShinyModule = require('./my-shiny-module').myShinyModule;
```

I wish someone would implement a webpack plugin that prepends slightly changed UMD pattern to fix this :sweat_smile:

**Comment by alferov** [comment]
> babel-core@5.8.33: Babel 5 is no longer being maintained. Upgrade to Babel 6.

Oh, wow.
I guess it's better to go with `module.exports = { … }`

**Comment by himalayafan** [comment]
It getting worse.... `babel-register` is now it's own package. Stripped out from the core. So a lot of 5.x code need a re-factoring.  https://www.npmjs.com/package/babel-register
